<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.29">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Model/Method Card: spotforecast2 – spotforecast2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bcbce66894bfa8e7e94e40e0186b9bb8.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-4e7a6ecc11b04d2331dcee725084a9de.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bcbce66894bfa8e7e94e40e0186b9bb8.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-655808e3c14d9b59497a1b5a58e1ce29.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-2dd548ee3eab68bd851dd9e3d9c9a811.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-655808e3c14d9b59497a1b5a58e1ce29.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">spotforecast2</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sequential-parameter-optimization/spotforecast2"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../docs/safe/MODEL_CARD.html">Model Card</a></li><li class="breadcrumb-item"><a href="../../docs/safe/MODEL_CARD.html">Model/Method Card</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">API Reference</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Warnings</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/warnings.exceptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">exceptions</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/models.forecaster_recursive_model_full.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">forecaster_recursive_model_full</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/models.forecaster_recursive_lgbm_full.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">forecaster_recursive_lgbm_full</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/models.forecaster_recursive_xgb_full.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">forecaster_recursive_xgb_full</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/models.forecaster_recursive_catboost_full.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">forecaster_recursive_catboost_full</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Multitask</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.agg_predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">agg_predictor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.BaseTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BaseTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.LazyTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LazyTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.OptunaTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OptunaTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.SpotOptimTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SpotOptimTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.PredictTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PredictTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.CleanTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CleanTask</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/multitask.MultiTask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MultiTask</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Model Selection</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.bayesian_search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">bayesian_search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">boundary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.grid_search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">grid_search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.random_search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">random_search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.spotoptim_search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">spotoptim_search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/model_selection.utils_metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">utils_metrics</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Plots</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/plots.diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">diagnostics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/plots.outlier_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">outlier_plots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/plots.plotter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">plotter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/plots.time_series_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">time_series_visualization</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Stats</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/stats.autocorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">autocorrelation</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">ENTSO-E CLI</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/reference/entsoe_cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">entsoe_cli</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Processing Guides</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/processing/model_persistence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Persistence</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Plots Guides</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/plots/outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outlier Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/plots/time_series_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time Series Visualization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Model Selection Guides</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/model_selection/spotoptim_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intro to SpotOptim</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/model_selection/spotoptim_lags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SpotOptim Lag Handling</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Tasks Guide</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/tasks/multitask.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multitask Tutorial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/tasks/entsoe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ENTSO-E CLI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Multitask</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/multitask/entsoe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ENTSO-E single-target</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/multitask/multitask-II.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-Target Demo II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">Model Card</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../docs/safe/MODEL_CARD.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Model/Method Card</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#modelmethod-card-spotforecast2" id="toc-modelmethod-card-spotforecast2" class="nav-link active" data-scroll-target="#modelmethod-card-spotforecast2">Model/Method Card: spotforecast2</a>
  <ul class="collapse">
  <li><a href="#model-details" id="toc-model-details" class="nav-link" data-scroll-target="#model-details">1. Model Details</a></li>
  <li><a href="#intended-use-and-scope" id="toc-intended-use-and-scope" class="nav-link" data-scroll-target="#intended-use-and-scope">2. Intended Use and Scope</a></li>
  <li><a href="#how-to-get-started" id="toc-how-to-get-started" class="nav-link" data-scroll-target="#how-to-get-started">3. How to Get Started</a></li>
  <li><a href="#technical-specification" id="toc-technical-specification" class="nav-link" data-scroll-target="#technical-specification">4. Technical Specification</a>
  <ul class="collapse">
  <li><a href="#task-and-model-family" id="toc-task-and-model-family" class="nav-link" data-scroll-target="#task-and-model-family">Task and model family</a></li>
  <li><a href="#lag-construction" id="toc-lag-construction" class="nav-link" data-scroll-target="#lag-construction">Lag construction</a></li>
  <li><a href="#hyperparameter-search" id="toc-hyperparameter-search" class="nav-link" data-scroll-target="#hyperparameter-search">Hyperparameter search</a></li>
  <li><a href="#feature-attribution" id="toc-feature-attribution" class="nav-link" data-scroll-target="#feature-attribution">Feature attribution</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a></li>
  <li><a href="#training" id="toc-training" class="nav-link" data-scroll-target="#training">Training</a></li>
  <li><a href="#architecture-layered" id="toc-architecture-layered" class="nav-link" data-scroll-target="#architecture-layered">Architecture (layered)</a></li>
  <li><a href="#design-objectives" id="toc-design-objectives" class="nav-link" data-scroll-target="#design-objectives">Design objectives</a></li>
  </ul></li>
  <li><a href="#interfaces-and-runtime" id="toc-interfaces-and-runtime" class="nav-link" data-scroll-target="#interfaces-and-runtime">5. Interfaces and Runtime</a></li>
  <li><a href="#data-and-operational-design-domain" id="toc-data-and-operational-design-domain" class="nav-link" data-scroll-target="#data-and-operational-design-domain">6. Data and Operational Design Domain</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation">7. Evaluation</a></li>
  <li><a href="#model-transparency" id="toc-model-transparency" class="nav-link" data-scroll-target="#model-transparency">8. Model Transparency</a></li>
  <li><a href="#operation-monitoring-and-response" id="toc-operation-monitoring-and-response" class="nav-link" data-scroll-target="#operation-monitoring-and-response">9. Operation: Monitoring and Response</a></li>
  <li><a href="#compliance-support" id="toc-compliance-support" class="nav-link" data-scroll-target="#compliance-support">10. Compliance Support</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary">11. Glossary</a></li>
  <li><a href="#how-to-audit" id="toc-how-to-audit" class="nav-link" data-scroll-target="#how-to-audit">12. How to Audit</a></li>
  <li><a href="#citation-authors-and-contact" id="toc-citation-authors-and-contact" class="nav-link" data-scroll-target="#citation-authors-and-contact">13. Citation, Authors, and Contact</a></li>
  <li><a href="#disclaimer-and-liability" id="toc-disclaimer-and-liability" class="nav-link" data-scroll-target="#disclaimer-and-liability">14. Disclaimer and Liability</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sequential-parameter-optimization/spotforecast2/edit/main/docs/safe/MODEL_CARD.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sequential-parameter-optimization/spotforecast2/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../docs/safe/MODEL_CARD.html">Model Card</a></li><li class="breadcrumb-item"><a href="../../docs/safe/MODEL_CARD.html">Model/Method Card</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Model/Method Card: spotforecast2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="modelmethod-card-spotforecast2" class="level1">
<h1>Model/Method Card: spotforecast2</h1>
<p>This card describes what spotforecast2 is, how to use it, the conditions under which its results are valid, and how it relates to its safety-critical sibling spotforecast2-safe. It follows the Hugging Face Model Card Guidebook taxonomy (<a href="https://huggingface.co/docs/hub/model-card-guidebook">Ozoani et al., 2022</a>). Where the <a href="https://github.com/sequential-parameter-optimization/spotforecast2-safe/blob/main/MODEL_CARD.md"><code>spotforecast2-safe</code> model card</a> documents the deterministic, fail-safe core, this card documents the un-restricted superset built on top of it.</p>
<section id="model-details" class="level2">
<h2 class="anchored" data-anchor-id="model-details">1. Model Details</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Name</td>
<td>spotforecast2</td>
</tr>
<tr class="even">
<td>Version</td>
<td>3.3.0</td>
</tr>
<tr class="odd">
<td>Type</td>
<td>Full-featured forecasting toolkit: recursive multi-step forecasting plus hyperparameter tuning (Optuna, SpotOptim), interactive visualization (Plotly), and feature attribution via SHapley Additive exPlanations (SHAP). Un-restricted superset of <code>spotforecast2-safe</code>.</td>
</tr>
<tr class="even">
<td>Developed by</td>
<td>Thomas Bartz-Beielstein, ORCID <a href="https://orcid.org/0000-0002-5938-5158">0000-0002-5938-5158</a></td>
</tr>
<tr class="odd">
<td>Distributed by</td>
<td>the <code>sequential-parameter-optimization</code> GitHub organization</td>
</tr>
<tr class="even">
<td>Language</td>
<td>Python 3.13 or newer</td>
</tr>
<tr class="odd">
<td>License</td>
<td>AGPL-3.0-or-later (Affero General Public License)</td>
</tr>
<tr class="even">
<td>Built on</td>
<td><code>spotforecast2-safe</code> (<code>&gt;=15.0.0rc1,&lt;16</code>), imported and re-exported as <code>spotforecast2_safe</code></td>
</tr>
<tr class="odd">
<td>Repository</td>
<td><a href="https://github.com/sequential-parameter-optimization/spotforecast2" class="uri">https://github.com/sequential-parameter-optimization/spotforecast2</a></td>
</tr>
<tr class="even">
<td>Documentation</td>
<td><a href="https://sequential-parameter-optimization.github.io/spotforecast2/" class="uri">https://sequential-parameter-optimization.github.io/spotforecast2/</a></td>
</tr>
<tr class="odd">
<td>Technical report</td>
<td>the safe package’s <code>bart26h/index.qmd</code>, plus the rendered documentation above</td>
</tr>
</tbody>
</table>
<p>spotforecast2 inherits the deterministic forecasters, preprocessing, configuration, and data loaders from spotforecast2-safe and adds four capability groups that the safe package deliberately excludes: visualization (plotly, matplotlib, kaleido), hyperparameter search (optuna, spotoptim), explainability (shap), and ENTSO-E data access (entsoe-py). Several of these — Plotly, Matplotlib, Optuna, SpotOptim — are exactly the libraries the safe package lists as prohibited; spotforecast2 is where they are allowed to live.</p>
<p>Two Common Platform Enumeration (CPE) identifiers let vulnerability-tracking and software bill of materials (SBOM) tools recognize the package. The wildcard identifier <code>cpe:2.3:a:sequential_parameter_optimization:spotforecast2:*:*:*:*:*:*:*:*</code> matches any release; the current release is <code>cpe:2.3:a:sequential_parameter_optimization:spotforecast2:3.3.0:*:*:*:*:*:*:*</code>. Unlike the safe package, this repository ships no CPE-generating utility; the strings above are authoritative and maintained by hand.</p>
<p>spotforecast2 is, by design, a development and model-selection tool rather than a low-risk deterministic component. It introduces stochastic search, plotting backends, and a larger dependency tree, which place it outside the safe envelope. It is not the certified inference path for a high-risk AI system; that role belongs to spotforecast2-safe. Responsibilities are divided as follows.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Responsibility</th>
<th>Party</th>
<th>Contact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Toolkit development and maintenance</td>
<td>Thomas Bartz-Beielstein</td>
<td><code>bartzbeielstein@gmail.com</code></td>
</tr>
<tr class="even">
<td>Distribution</td>
<td>sequential-parameter-optimization on GitHub</td>
<td>repository issue tracker</td>
</tr>
<tr class="odd">
<td>Model selection and experimentation</td>
<td>the analyst using this package</td>
<td>per project</td>
</tr>
<tr class="even">
<td>Safety-critical deployment, operation, and audit</td>
<td>the system integrator, through <code>spotforecast2-safe</code></td>
<td>defined per deployment</td>
</tr>
</tbody>
</table>
<p>The current release is 3.3.0, tracking the stable public interface re-exported alongside <code>spotforecast2_safe</code>. The full version history, including release dates, is recorded in <code>CHANGELOG.md</code> and on the GitHub Releases page; it is maintained automatically by the release pipeline and is not repeated here.</p>
</section>
<section id="intended-use-and-scope" class="level2">
<h2 class="anchored" data-anchor-id="intended-use-and-scope">2. Intended Use and Scope</h2>
<p>spotforecast2 supports exploratory and applied forecasting of hourly electricity load and spot prices on ENTSO-E data, end to end, through the <code>spotforecast2-entsoe</code> console script. Its distinctive capabilities are hyperparameter search — Bayesian search over lags, window features, and regressor parameters with Optuna (<code>bayesian_search_forecaster</code>), or surrogate-model search with SpotOptim (<code>spotoptim_search_forecaster</code>) — interactive inspection through Plotly figures, and global SHAP feature importances via <code>shap.TreeExplainer</code>. The <code>MultiTask</code> dispatcher and the <code>run()</code> entry point orchestrate multi-target pipelines: per-target data preparation, outlier handling, imputation, feature engineering, tuning, and prediction.</p>
<p>The intended downstream use is development and model selection: choosing lag windows and regressor hyperparameters here, then promoting the validated configuration into a spotforecast2-safe deployment for the deterministic inference path. Tuned <code>ForecasterRecursiveLGBMFull</code> and <code>ForecasterRecursiveXGBFull</code> models, or just their best parameters, also feed research notebooks and reporting.</p>
<p>The scope has firm limits. spotforecast2 is deliberately not the certified, fail-safe inference layer: it introduces stochastic search, heavier third-party dependencies, and plotting backends. For high-risk, auditable, bit-for-bit reproducible deployment, use spotforecast2-safe. The visualization layer is for human inspection, not for driving automated control loops. Search budgets (<code>n_trials</code>, surrogate evaluations) must be bounded; an open-ended search is not an inference contract.</p>
</section>
<section id="how-to-get-started" class="level2">
<h2 class="anchored" data-anchor-id="how-to-get-started">3. How to Get Started</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install spotforecast2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Tune a LightGBM forecaster with Optuna, then inspect feature importances with SHAP:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotforecast2.models <span class="im">import</span> ForecasterRecursiveLGBMFull</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># iteration indexes the training run; n_trials bounds the Optuna budget.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> ForecasterRecursiveLGBMFull(iteration<span class="op">=</span><span class="dv">0</span>, n_trials<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>model.tune()  <span class="co"># load data, Bayesian search, refit with best params, auto-persist</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>importances <span class="op">=</span> model.get_global_shap_feature_importance(frac<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(importances.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Run a complete multi-target pipeline programmatically via <code>run()</code>, or use the bundled console script:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">spotforecast2-entsoe</span>      <span class="co"># ENTSO-E download / train / predict (needs ENTSOE_API_KEY)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="technical-specification" class="level2">
<h2 class="anchored" data-anchor-id="technical-specification">4. Technical Specification</h2>
<section id="task-and-model-family" class="level3">
<h3 class="anchored" data-anchor-id="task-and-model-family">Task and model family</h3>
<p>spotforecast2 addresses recursive multi-step forecasting of a univariate series from its own lags, rolling-window features, and exogenous regressors, using the same scikit-learn-compatible wrappers as the safe core. On top of that deterministic base it adds three capability layers: hyperparameter search, feature attribution, and visualization.</p>
</section>
<section id="lag-construction" class="level3">
<h3 class="anchored" data-anchor-id="lag-construction">Lag construction</h3>
<p>The sliding-window (N-to-1) lag transformation, which builds one feature row per target value without ever placing the target in its own feature row, is inherited unchanged from spotforecast2-safe; see that package’s model card for the mathematical description. spotforecast2 does not re-implement it.</p>
</section>
<section id="hyperparameter-search" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-search">Hyperparameter search</h3>
<p>Two interchangeable engines optimize the forecaster over a search space of candidate lags (<code>LAGS_CONSIDER</code>), rolling window features (<code>WINDOW_FEATURES</code>: mean, min, and max over 24 h, 168 h, and 720 h), and regressor parameters (<code>SEARCH_SPACES</code>):</p>
<ul>
<li><strong>Bayesian search</strong> (<code>bayesian_search_forecaster</code>) wraps Optuna’s Tree-structured Parzen Estimator (TPE) sampler.</li>
<li><strong>Surrogate search</strong> (<code>spotoptim_search_forecaster</code>) uses SpotOptim, fitting a surrogate model to propose configurations with fewer evaluations.</li>
</ul>
<p>Both are scored by <code>backtesting_forecaster</code> over the time-aware folds (<code>TimeSeriesFold</code>, <code>OneStepAheadFold</code>) re-exported from the safe core, so the evaluation protocol is identical to the deterministic library — only the search around it is added.</p>
</section>
<section id="feature-attribution" class="level3">
<h3 class="anchored" data-anchor-id="feature-attribution">Feature attribution</h3>
<p><code>get_global_shap_feature_importance(frac)</code> runs <code>shap.TreeExplainer</code> on the fitted tree estimator over a sampled fraction of the training matrix and returns mean absolute SHAP values per feature, sorted descending. An untuned model returns an empty series rather than failing.</p>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">Visualization</h3>
<p><code>PredictionFigure</code> and the helpers in <code>plots/</code> render actual-vs-predicted traces, outlier overlays, distributions, and periodograms as interactive Plotly figures; <code>kaleido</code> provides static image export.</p>
</section>
<section id="training" class="level3">
<h3 class="anchored" data-anchor-id="training">Training</h3>
<p>Unlike the safe core, which trains nothing on its own, spotforecast2 performs real training during a tuning session. The <code>Full</code> forecasters override the safe-package <code>tune()</code> stub with an Optuna or SpotOptim search and refit with the best configuration, then auto-persist the model so the predict-only path (<code>PredictTask</code>) loads it without re-tuning. A single session runs many fits — one per Optuna trial or surrogate evaluation, multiplied across folds, targets, and iterations — so the training cost is a function of the search budget rather than a fixed quantity.</p>
</section>
<section id="architecture-layered" class="level3">
<h3 class="anchored" data-anchor-id="architecture-layered">Architecture (layered)</h3>
<p><code>forecaster/</code> (estimator wrappers plus metrics, re-exported from the safe core) → <code>preprocessing/</code> (outlier detection and ported transformers) → <code>model_selection/</code> (<code>grid_search</code>, <code>random_search</code>, <code>bayesian_search</code>, <code>spotoptim_search</code>) → <code>models/</code> (the <code>Full</code> forecasters <code>ForecasterRecursiveModelFull</code>, <code>ForecasterRecursiveLGBMFull</code>, <code>ForecasterRecursiveXGBFull</code>, which override the safe-package <code>tune()</code> and <code>get_global_shap_feature_importance()</code> stubs) → <code>multitask/</code> (the <code>BaseTask</code> hierarchy and the <code>MultiTask</code> dispatcher) → <code>plots/</code> (Plotly visualization) → <code>tasks/</code> (console-script entry points).</p>
</section>
<section id="design-objectives" class="level3">
<h3 class="anchored" data-anchor-id="design-objectives">Design objectives</h3>
<ul>
<li><strong>Extends, never shadows</strong>: spotforecast2 overrides only the explicit extension points (<code>tune</code>, <code>get_global_shap_feature_importance</code>) of the safe core. It does not re-implement deterministic logic with a permissive variant.</li>
<li><strong>Reproducible, not deterministic</strong>: a search is repeatable given a fixed <code>random_state</code>, dependency set, and data window — a weaker guarantee than the safe core’s bit-for-bit determinism, and an intentional one.</li>
</ul>
</section>
</section>
<section id="interfaces-and-runtime" class="level2">
<h2 class="anchored" data-anchor-id="interfaces-and-runtime">5. Interfaces and Runtime</h2>
<p>The input and output contract is inherited from the safe core. The target is a numeric univariate series on a regular, monotonic date-time index; exogenous features are a complete numeric frame aligned to that index, and any missing exogenous entry raises a <code>ValueError</code> before a prediction is made. Forecasts are returned as a series whose length equals the requested horizon, in the target’s units. Fitted forecasters are serialized with joblib and reloaded through the same persistence helpers, so a tuned model produced here loads unchanged in a spotforecast2-safe predict path.</p>
<p>spotforecast2 runs on Python 3.13 or newer on a central processing unit (CPU); it needs no graphics processing unit (GPU) and ships no GPU code. No pretrained weights are shipped.</p>
<p>The added capabilities bring their own dependencies. All but one carry permissive licenses; SpotOptim is copyleft (AGPL-3.0-or-later), consistent with spotforecast2’s own license but a difference from the safe core’s all-permissive runtime.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dependency</th>
<th>Capability</th>
<th>License</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>plotly</td>
<td>interactive visualization</td>
<td>MIT</td>
</tr>
<tr class="even">
<td>matplotlib</td>
<td>static visualization</td>
<td>Python Software Foundation</td>
</tr>
<tr class="odd">
<td>kaleido</td>
<td>static image export</td>
<td>MIT</td>
</tr>
<tr class="even">
<td>optuna</td>
<td>Bayesian hyperparameter search</td>
<td>MIT</td>
</tr>
<tr class="odd">
<td>spotoptim</td>
<td>surrogate hyperparameter search</td>
<td>AGPL-3.0-or-later</td>
</tr>
<tr class="even">
<td>shap</td>
<td>feature attribution</td>
<td>MIT</td>
</tr>
<tr class="odd">
<td>entsoe-py</td>
<td>ENTSO-E data access</td>
<td>MIT</td>
</tr>
</tbody>
</table>
<p>These additions enlarge the Common Vulnerabilities and Exposures (CVE) attack surface relative to the minimal safe core; track the full dependency tree, including transitive dependencies, in your SBOM. Compute cost is dominated by the tuning search, not by inference: a single forecast is cheap, but a large <code>n_trials</code> over many targets runs proportionally many model fits and is materially more expensive than one deterministic forecast. The work stays CPU-only; bound the search budget to control cost and energy use.</p>
</section>
<section id="data-and-operational-design-domain" class="level2">
<h2 class="anchored" data-anchor-id="data-and-operational-design-domain">6. Data and Operational Design Domain</h2>
<p>The Operational Design Domain (ODD) is the set of conditions under which the toolkit’s results are valid. spotforecast2 inherits the safe core’s data ODD and adds conditions specific to tuning and attribution. Outside these conditions the inherited layers raise an error rather than return an unreliable result; the added search and attribution layers instead lose trustworthiness, which is why the recommendations below matter.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Valid range</th>
<th>Outside the range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Target series</td>
<td>numeric, univariate, regular monotonic date-time index</td>
<td>error (inherited)</td>
</tr>
<tr class="even">
<td>Exogenous features</td>
<td>numeric, complete, aligned to the target index</td>
<td><code>ValueError</code> on any missing entry (inherited)</td>
</tr>
<tr class="odd">
<td>Sampling interval</td>
<td>uniform; hourly in the demos</td>
<td>unreliable result</td>
</tr>
<tr class="even">
<td>Minimum history</td>
<td>longer than the window size plus the number of lags</td>
<td>the model cannot be called</td>
</tr>
<tr class="odd">
<td>Search budget</td>
<td>bounded <code>n_trials</code> / surrogate evaluations</td>
<td>unbounded search is not an inference contract</td>
</tr>
<tr class="even">
<td>Reproducibility</td>
<td>fixed <code>random_state</code>, pinned dependency versions and data window</td>
<td>the selected model may change between runs</td>
</tr>
<tr class="odd">
<td>Tuning validation</td>
<td>held-out ground truth beyond the backtest folds</td>
<td>overfitting to the validation window</td>
</tr>
<tr class="even">
<td>SHAP attribution</td>
<td>computed on a sampled fraction (<code>frac</code>) of training data</td>
<td>values indicate, but do not prove, feature relevance</td>
</tr>
</tbody>
</table>
<p>Two risks follow from the added layers. Optimizing lags and hyperparameters against a limited number of backtest folds can select a configuration that fits the validation window rather than the underlying process, so held-out evaluation is mandatory before a configuration is trusted. And because Optuna’s sampler, the SpotOptim surrogate search, and SHAP’s subsampling are stochastic, a fixed <code>random_state</code> makes a run reproducible, but changing the search budget, the data window, or a dependency version can change the selected model — the deliberate opposite of the safe core’s bit-for-bit determinism. All feature-engineering caveats of the safe core — regressor drift, leakage when bypassing the provided builders, and large-series memory cost — apply here unchanged.</p>
<p>To stay inside the valid domain: validate every tuned configuration against historical ground truth on a held-out horizon, pin <code>random_state</code> and record exact dependency versions, bound the search budget explicitly, and route the production inference path through spotforecast2-safe.</p>
</section>
<section id="evaluation" class="level2">
<h2 class="anchored" data-anchor-id="evaluation">7. Evaluation</h2>
<p>Two evaluation targets apply: forecasting accuracy (the tuned models) and software quality (the toolkit). Tuning is scored by <code>backtesting_forecaster</code> over <code>TimeSeriesFold</code> and <code>OneStepAheadFold</code>, so a configuration’s forecasting error is measured on time-aware folds that never leak future data into a past prediction. The <code>Full</code> forecasters run a complete Optuna or SpotOptim search and refit with the best configuration, auto-persisting the result so the predict-only path loads it without re-tuning; global SHAP importances are produced for fitted tree models, and an unfitted or untuned model returns an empty series rather than raising.</p>
<p>The toolkit itself is evaluated on software-quality properties: docstring examples in <code>src/</code> are executed by the test suite, unit and integration fixtures live under <code>tests/</code>, reproducibility of a search is checked against a fixed <code>random_state</code>, and new code carries coverage matching the CI configuration. Unlike the safe core, spotforecast2 ships no CPE-generation test — the CPE strings in Section 1 are maintained by hand — and its cybersecurity footprint is deliberately larger, the trade-off for interactive, exploratory use.</p>
</section>
<section id="model-transparency" class="level2">
<h2 class="anchored" data-anchor-id="model-transparency">8. Model Transparency</h2>
<p>spotforecast2 produces point forecasts. It does not natively quantify or calibrate predictive uncertainty, so a deployment that needs prediction intervals or calibrated probabilities must add them in the downstream regressor or a wrapper around it — a limitation inherited from the safe core.</p>
<p>Where the safe package deliberately ships no explainability backend, spotforecast2 adds one: <code>get_global_shap_feature_importance</code> exposes global SHAP attributions from <code>shap.TreeExplainer</code> on top of the regressor’s own split- and gain-based importances. The code remains white-box — no compiled inference kernels, no opaque weights — and the docstrings are executable, so every transformation and every attribution can be read and audited in source.</p>
</section>
<section id="operation-monitoring-and-response" class="level2">
<h2 class="anchored" data-anchor-id="operation-monitoring-and-response">9. Operation: Monitoring and Response</h2>
<p>A deployment that uses spotforecast2 during development should watch the quality of incoming data (missing or out-of-range values and timestamp gaps), the drift of the input and target distributions away from the tuning period, and the forecast error against a simple seasonal baseline. The ENTSO-E task enforces a retraining-cadence gate through the configuration’s <code>retrain_max_age</code>: a model older than the configured age triggers a retrain, and the <code>--force</code> flag bypasses the gate when an immediate refit is wanted. A module-level logger records timestamped events for audit retention.</p>
<p>When monitoring crosses a deployment-defined threshold, the usual responses are to retune or retrain, to fall back to the seasonal baseline or the last known-good model, and to alert the responsible team. Once a validated configuration is promoted to a spotforecast2-safe deployment, the integrator owns the thresholds and escalation steps for the safety-critical inference path.</p>
</section>
<section id="compliance-support" class="level2">
<h2 class="anchored" data-anchor-id="compliance-support">10. Compliance Support</h2>
<p>spotforecast2 is not the path to compliance for a high-risk AI system — that role belongs to spotforecast2-safe. The intended division of labor under the EU AI Act (Regulation (EU) 2024/1689) is to use spotforecast2 during development — explore data, search hyperparameters, visualize candidates, and attribute feature importance — and then promote the validated configuration (lags, window features, regressor parameters) into a spotforecast2-safe deployment, which provides the deterministic, fail-safe, auditable inference path.</p>
<p>For the authoritative article-by-article mapping (Article 10 data governance, Article 11 technical documentation, Article 12 logging, Article 13 transparency, Article 15 accuracy and robustness) to IEC 61508, ISO 26262, and ISA/IEC 62443, consult the spotforecast2-safe model card and its technical report (<code>bart26h/index.qmd</code>). Within its own scope, spotforecast2 keeps the transparency properties of the safe core: white-box code, executable docstrings, and open, inspectable SHAP attributions. The stochastic tuning, plotting backends, and enlarged dependency surface are precisely what place this package outside the safe envelope by design.</p>
</section>
<section id="glossary" class="level2">
<h2 class="anchored" data-anchor-id="glossary">11. Glossary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Optuna</td>
<td>Hyperparameter-optimization framework; here used through its TPE sampler.</td>
</tr>
<tr class="even">
<td>SpotOptim</td>
<td>Surrogate-model-based optimizer (Sequential Parameter Optimization) used as an alternative to Optuna for hyperparameter search.</td>
</tr>
<tr class="odd">
<td>Surrogate model</td>
<td>A cheap approximation of the expensive objective (here, backtest error) that the optimizer queries to propose new configurations with fewer full evaluations.</td>
</tr>
<tr class="even">
<td>Backtesting</td>
<td>Evaluation of a forecaster by replaying it over historical, time-aware folds (<code>TimeSeriesFold</code>, <code>OneStepAheadFold</code>).</td>
</tr>
<tr class="odd">
<td>IEC 61508 / ISO 26262 / ISA·IEC 62443</td>
<td>Functional-safety and industrial-security standards relevant to the spotforecast2-safe compliance path, not to this package. See the safe-package model card.</td>
</tr>
</tbody>
</table>
</section>
<section id="how-to-audit" class="level2">
<h2 class="anchored" data-anchor-id="how-to-audit">12. How to Audit</h2>
<p>spotforecast2 intentionally ships the libraries that spotforecast2-safe prohibits, so the audit goal is not dependency minimization but correct separation of concerns.</p>
<ol type="1">
<li>Confirm that spotforecast2 is used for development and model selection, and that the safety-critical inference path runs on spotforecast2-safe — not on this package.</li>
<li>Run <code>uv run pytest tests/</code> to verify the tuning, attribution, and visualization code.</li>
<li>Check that tuning runs pin <code>random_state</code> (and record dependency versions) wherever reproducibility is required.</li>
<li>Record the CPE identifiers from Section 1 in vulnerability-tracking systems and SBOM disclosures. Unlike the safe package, this repository ships no CPE-generating utility or test — the strings in Section 1 are authoritative.</li>
<li>Run <code>uv tool run reuse lint</code> to confirm SPDX and REUSE license-header compliance.</li>
</ol>
</section>
<section id="citation-authors-and-contact" class="level2">
<h2 class="anchored" data-anchor-id="citation-authors-and-contact">13. Citation, Authors, and Contact</h2>
<p>Maintainer: Thomas Bartz-Beielstein, ORCID <a href="https://orcid.org/0000-0002-5938-5158">0000-0002-5938-5158</a>, <code>bartzbeielstein@gmail.com</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="va">@misc</span>{<span class="ot">spotforecast2</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>       = {Bartz-Beielstein, Thomas},</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>        = {{spotforecast2}: Forecasting Toolkit with Tuning, Visualization, and Explainability},</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>         = {2026},</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">howpublished</span> = {<span class="ch">\url</span>{https://github.com/sequential-parameter-optimization/spotforecast2}},</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">note</span>         = {AGPL-3.0-or-later}</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Or as a formatted reference: Bartz-Beielstein, T. (2026). <em>spotforecast2: Forecasting toolkit with tuning, visualization, and explainability</em> (Version 3.3.0) [Computer software]. https://github.com/sequential-parameter-optimization/spotforecast2</p>
<p>The long-form design rationale, compliance mapping, and evaluation protocol live in the spotforecast2-safe technical report (<code>bart26h/index.qmd</code>).</p>
</section>
<section id="disclaimer-and-liability" class="level2">
<h2 class="anchored" data-anchor-id="disclaimer-and-liability">14. Disclaimer and Liability</h2>
<p><strong>Limitation of liability.</strong> This software is provided “AS IS” without any warranties. The developers and contributors assume no liability for any direct or indirect damages, system failures, or financial losses resulting from its use.</p>
<p>spotforecast2 is an exploratory and model-selection toolkit and is not intended for safety-critical deployment. For production or safety-critical use, deploy spotforecast2-safe and perform a full system-level safety validation (for example under ISO 26262, IEC 61508, or the EU AI Act) before going live.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/sequential-parameter-optimization\.github\.io\/spotforecast2\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright © 2024-2026 bartzbeielstein | <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0-or-later</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sequential-parameter-optimization/spotforecast2/edit/main/docs/safe/MODEL_CARD.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sequential-parameter-optimization/spotforecast2/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>