"""Pre-render script: extract project version → _variables.yml.

This script is registered as a Quarto pre-render hook in _quarto.yml:

    project:
      pre-render: docs/pre-render.py

Quarto runs it automatically before every ``quarto render`` call, which means
``{{< var version >}}`` and ``{{< var version_badge >}}`` resolve correctly in
any ``.qmd`` file without manual version tagging.

Safety-critical note
--------------------
This script uses only the Python standard library (``tomllib``, ``pathlib``).
It has no external dependencies and will never fail silently — any read/write
error is raised immediately, aborting the render.

``tomllib`` is available in Python ≥ 3.11 (PEP 680).  The project requires
Python ≥ 3.13, so no back-compat shim is needed.
"""

import pathlib
import tomllib

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
# This script lives at  docs/pre-render.py
# pyproject.toml lives at  <project-root>/pyproject.toml
# _variables.yml is written at  <project-root>/_variables.yml
ROOT: pathlib.Path = pathlib.Path(__file__).parent.parent.resolve()
PYPROJECT: pathlib.Path = ROOT / "pyproject.toml"
VARIABLES_OUT: pathlib.Path = ROOT / "_variables.yml"


def main() -> None:
    """Extract version and write _variables.yml (idempotent)."""
    # -- Read pyproject.toml -------------------------------------------------
    if not PYPROJECT.exists():
        raise FileNotFoundError(
            f"pyproject.toml not found at {PYPROJECT}. "
            "Cannot determine project version for documentation build."
        )

    with PYPROJECT.open("rb") as fh:
        data = tomllib.load(fh)

    version: str = data["project"]["version"]

    # -- Write _variables.yml (only if content changed) ----------------------
    # IMPORTANT: quarto preview watches for file changes and triggers a full
    # site reload whenever any file is written.  Writing _variables.yml on
    # every page navigation would cause an infinite reload loop.  This check
    # makes the script a no-op when the version has not changed.
    content = (
        "# Auto-generated by docs/pre-render.py — DO NOT EDIT MANUALLY.\n"
        "# This file is overwritten on every `quarto render` call.\n"
        f'version: "{version}"\n'
        f'version_badge: "{version}"\n'
    )

    if VARIABLES_OUT.exists() and VARIABLES_OUT.read_text(encoding="utf-8") == content:
        print(f"[pre-render] _variables.yml unchanged — skipping write (version={version})")
        return

    VARIABLES_OUT.write_text(content, encoding="utf-8")
    print(f"[pre-render] _variables.yml written — version={version}")


if __name__ == "__main__":
    main()
